#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
if [[ -t 0 || -t 1 ]]; then
  if hash fortune 2>/dev/null; then
    if hash cowsay 2>/dev/null; then
      if hash lolcat 2>/dev/null; then
        fortune -s | cowsay | lolcat
        print
      else
        fortune -s | cowsay
        print
      fi
    else
      fortune -s
      print
    fi
  fi
fi