#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

bindkey -e

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path manpath

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
 $HOME/bin
 $HOME/anaconda3/bin
 /usr/local/{bin,sbin}
 /usr/local/opt/coreutils/libexec/gnubin
 /usr/texbin
 /usr/local/share/john
 $path
)

manpath=(
 /usr/local/opt/coreutils/libexec/gnuman
 $manpath
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-g -i -M -R -S -w -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

## Languages (Python, Ruby, Node, PHP, Java, Android, R)

# Python
export NLTK_DATA="~/nltk_data"

# Ruby
if which rbenv > /dev/null; then eval "$(rbenv init --no-rehash - zsh)"; fi

# Java
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
# launchctl `echo setenv JAVA_HOME $JAVA_HOME`

# export CLASSPATH="/Users/johria/stanford_nlp/slf4j-1.7.18/*"
export CLASSPATH="/Users/johria/stanford_nlp/stanford-ner-2015-12-09/stanford-ner.jar"
export CLASSPATH="$CLASSPATH:/Users/johria/stanford_nlp/stanford-parser-full-2015-12-09/stanford-parser.jar"
export CLASSPATH="$CLASSPATH:/Users/johria/stanford_nlp/stanford-postagger-full-2015-12-09/stanford-postagger.jar"

export STANFORD_MODELS="/Users/johria/stanford_nlp/stanford-ner-2015-12-09/classifiers"
export STANFORD_MODELS="$STANFORD_MODELS:/Users/johria/stanford_nlp/stanford-postagger-full-2015-12-09/models"
export STANFORD_MODELS="$STANFORD_MODELS:/Users/johria/stanford_nlp/stanford-parser-full-2015-12-09/stanford-parser-3.6.0-models.jar"

# Android
export ANDROID_HOME=/usr/local/opt/android-sdk
# export ANDROID_SDK_ROOT=ANDROID_HOME/??????
# launchctl `echo setenv ANDROID_SDK_ROOT $ANDROID_SDK_ROOT`

# R
if which Rscript > /dev/null; then
  export R_HOME=/usr/local/opt/r/R.framework/Resources
  export RSTUDIO_WHICH_R=/usr/local/bin/R
  # launchctl `echo setenv RSTUDIO_WHICH_R $RSTUDIO_WHICH_R`
fi

alias rstudio=~/Applications/RStudio.app/Contents/MacOS/RStudio

# Spark
export SPARK_HOME="/usr/local/opt/apache-spark/libexec/"
export PYSPARK_PYTHON="python3.5"

# Homebrew

export HOMEBREW_GITHUB_API_TOKEN="ae870fcbbae7516630c46ccb4fb87bf06575db09"

