#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

disable r

setopt histignorespace

alias grep="/usr/local/bin/grep $GREP_OPTIONS"
unset GREP_OPTIONS

alias dog='pygmentize -g'
eval "$(hub alias -s)"
alias findf='mdfind -onlyin . -name'
alias ff='find . -type f -name'
alias fd='find . -type d -name'
alias cp='cp -iv'
alias rm='rm -i'
alias mv='mv -i'
alias gst='git status'

# eval `/usr/libexec/path_helper -s`

# function project_aware_subl {
#    project_file=$(ls *.sublime-project 2>/dev/null | head -n 1)
#    subl ${*:-${project_file:-.}}
# }
# alias subl="project_aware_subl"

source /usr/local/share/zsh/site-functions/_aws
